# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 457e957fcc713f373c817dcbd4caa4eb2551180e2e560036c1b28835622d7b4c5316dfb346b9d58d88d3cc88a4189c285e9764dd9f0ea267e521f4f9e6890fb2

test:
  secret_key_base: 1b84fae0e52aa48ca0a4750aeaf5e62b3ac7ce9ad6bbcbfb9bb6a5f7c4dee6a34db834db950da77f07629d9f492d150b976cd86dbd4393967ded1df5f7cc76f7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
