# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f2ab77f86cb7430b776381dd37a2c3da92057737b678fb6e312096d13a6485150ad65c5ad5a2dbc9fbaf33d8eb2fb9c8c91a481fff870cb76835b8aa9cdf0ae6

test:
  secret_key_base: 7faf6d325cc2d9554f47a5b6467b1c8ff2180349e7113a56db6738cc55e1682e5107403f47992f486900f91d75c6cb261dd4cd2cb2e33133b33f7aae0fe7538e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
