# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 46418e3db4f8cb1e5b05bf22d33b20eaf086acc278495ef13abe02073fc4c9e52b227e4e8160bce1b0834ce57c6bbc1b2f61e023ef69a466bc3b6c5328dc55f6

test:
  secret_key_base: 8c55aa912d1aceb46bb7d9f9b2aa650357f0b9721841a4ed9833e9bda7efb98cc4d820ede8ab8e21f45a88371b0db27a8c36d7c7d0ddd2ad1bc6716fc6b985ec

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
